In [ ]:
import numpy as np

n = 3
extra = np.array([[1/2, 1/2, 0], [1/2, 0, 1], [0, 1/2, 0]])
print("Matrix:\n",extra)
limit = 0.000000001
rj = np.array([1/n,1/n,1/n])
for _ in range(100):
  new_rj = np.dot(extra, rj)
  print(new_rj)
  if np.linalg.norm(new_rj - rj) < limit:
    break
  rj = new_rj
print("\nFinal Matrix:\n",rj)

Matrix:
 [[0.5 0.5 0. ]
 [0.5 0.  1. ]
 [0.  0.5 0. ]]
[0.33333333 0.5        0.16666667]
[0.41666667 0.33333333 0.25      ]
[0.375      0.45833333 0.16666667]
[0.41666667 0.35416667 0.22916667]
[0.38541667 0.4375     0.17708333]
[0.41145833 0.36979167 0.21875   ]
[0.390625   0.42447917 0.18489583]
[0.40755208 0.38020833 0.21223958]
[0.39388021 0.41601562 0.19010417]
[0.40494792 0.38704427 0.20800781]
[0.39599609 0.41048177 0.19352214]
[0.40323893 0.39152018 0.20524089]
[0.39737956 0.40686035 0.19576009]
[0.40211995 0.39444987 0.20343018]
[0.39828491 0.40449015 0.19722493]
[0.40138753 0.39636739 0.20224508]
[0.39887746 0.40293884 0.1981837 ]
[0.40090815 0.39762243 0.20146942]
[0.39926529 0.4019235  0.19881121]
[0.40059439 0.39844386 0.20096175]
[0.39951913 0.40125895 0.19922193]
[0.40038904 0.39898149 0.20062947]
[0.39968526 0.40082399 0.19949075]
[0.40025463 0.39933338 0.200412  ]
[0.399794   0.40053931 0.19966669]
[0.40016666 0.39956369 0.20026965]
[0.39986517 0.40035298 0.19978185]


In [ ]:
# Google Matrix A = ß * M + (1 -ß) [1/N]

import numpy as np

n = 3
beta = 0.8
M = np.array([[1/2, 1/2, 0], [1/2, 0, 0], [0, 1/2, 1]])
A = beta*M + (1-beta)*np.full((3, 3), 1/n)
print("\nMatrix M:\n",M)
print("\nMatrix A:\n",A)
limit = 0.00000000000000000001
rj = np.array([1/n,1/n,1/n])
while True:
  new_rj = np.dot(A, rj)
  print(new_rj)
  if np.linalg.norm(new_rj - rj) < limit:
    break
  rj = new_rj
print("\nFinal Matrix:\n",rj)


Matrix M:
 [[0.5 0.5 0. ]
 [0.5 0.  0. ]
 [0.  0.5 1. ]]

Matrix A:
 [[0.46666667 0.46666667 0.06666667]
 [0.46666667 0.06666667 0.06666667]
 [0.06666667 0.46666667 0.86666667]]
[0.33333333 0.2        0.46666667]
[0.28 0.2  0.52]
[0.25866667 0.17866667 0.56266667]
[0.2416     0.17013333 0.58826667]
[0.23136    0.16330667 0.60533333]
[0.22453333 0.15921067 0.616256  ]
[0.22016427 0.15648    0.62335573]
[0.21732437 0.15473237 0.62794325]
[0.21548937 0.15359642 0.63091422]
[0.21430098 0.15286241 0.63283661]
[0.21353202 0.15238706 0.63408092]
[0.2130343  0.15207948 0.63488622]
[0.21271218 0.15188039 0.63540744]
[0.21250369 0.15175154 0.63574477]
[0.21236876 0.15166814 0.6359631 ]
[0.21228143 0.15161417 0.6361044 ]
[0.21222491 0.15157924 0.63619586]
[0.21218832 0.15155663 0.63625505]
[0.21216465 0.151542   0.63629336]
[0.21214932 0.15153253 0.63631815]
[0.21213941 0.1515264  0.6363342 ]
[0.21213299 0.15152243 0.63634458]
[0.21212883 0.15151986 0.6363513 ]
[0.21212614 0.1515182  0.63635566]